# Output Data and Plots 
DSN_OUT_SPEAKER_MATRIX      = "S"
DSN_OUT_DECODING_MATRIX     = "D"
DSN_OUT_ENCODING_MATRIX     = "G"
DSN_OUT_TRANSCODING_MATRIX  = "T_optimized"
DSN_OUT_OUTPUT_LAYOUT       = "output_layout"
DSN_OUT_CLOUD               = "cloud"

DSN_PLT_ENERGY                  = "e_base_64"
DSN_PLT_PRESSURE                = "pressure_base_64"
DSN_PLT_RADIAL_INTENSITY        = "ri_base_64"
DSN_PLT_TRANSVERSE_INTENSITY    = "ti_base_64"
DSN_PLT_ANGULAR_ERROR           = "ae_base_64"
DSN_PLT_SOURCE_WIDTH            = "sw_base_64"
DSN_PLT_ACCCENT_COLOUR          = "#ee9b00"
DSN_PLT_PRIMARY_BG_COLOUR       = "#15191F"
DSN_PLT_SECONDARY_BG_COLOUR     = "#202731"
DSN_PLT_TEXT_COLOUR             = "#ffffff"
DSN_PLT_LINE_COLOUR             = "#ffffff"

DSN_PLT_GRADIENT_COOL           = "#0f4c5c"
DSN_PLT_GRANDIENT_NEUTRAL       = "#fb8b24"
DSN_PLT_GRADIENT_WARM           = "#5f0f40"

DSN_PLT_ENERGY_TITLE            = "Energy"
DSN_PLT_PRESSURE_TITLE          = "Pressure"
DSN_PLT_RADIAL_I_TITLE          = "Radial Intensity"
DSN_PLT_TRANSVERSE_I_TITLE      = "Transverse Intensity"
DSN_PLT_RADIAL_V_TITLE          = "Radial Velocity"
DSN_PLT_TRANSVERSE_V_TITLE      = "Transverse Velocity"
DSN_PLT_ANGULAR_ERROR_TITLE     = "Angular Error"
DSN_PLT_SOURCE_WIDTH_TITLE      = "Source Width"